---
- name: Create reader training user
  community.mongodb.mongodb_user:
    login_host: "127.0.0.1"
    login_port: "{{ mongodb_port }}"
    login_database: admin
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ vault_mongodb_admin_password }}"
    database: admin
    name: "{{ mongodb_reader_user }}"
    password: "{{ vault_reader_password }}"
    roles:
      - db: "{{ mongodb_training_db }}"
        role: "{{ mongodb_reader_role }}"
    state: present
    update_password: on_create
  vars:
    ansible_python_interpreter: /opt/ansible-mongodb/bin/python
  no_log: true

- name: Create writer training user
  community.mongodb.mongodb_user:
    login_host: "127.0.0.1"
    login_port: "{{ mongodb_port }}"
    login_database: admin
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ vault_mongodb_admin_password }}"
    database: admin
    name: "{{ mongodb_writer_user }}"
    password: "{{ vault_writer_password }}"
    roles:
      - db: "{{ mongodb_training_db }}"
        role: "{{ mongodb_writer_role }}"
    state: present
    update_password: on_create
  vars:
    ansible_python_interpreter: /opt/ansible-mongodb/bin/python
  no_log: true

- name: Create library training user
  community.mongodb.mongodb_user:
    login_host: "127.0.0.1"
    login_port: "{{ mongodb_port }}"
    login_database: admin
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ vault_mongodb_admin_password }}"
    database: admin
    name: "{{ mongodb_library_user }}"
    password: "{{ vault_library_password }}"
    roles:
      - db: "{{ mongodb_library_db }}"
        role: "{{ mongodb_library_role }}"
    state: present
    update_password: on_create
  vars:
    ansible_python_interpreter: /opt/ansible-mongodb/bin/python
  no_log: true

- name: Report training users creation
  ansible.builtin.debug:
    msg: "Training MongoDB users were created and assigned custom roles by Ansible"
