---
- name: Install and configure MongoDB
  ansible.builtin.import_tasks: setup.yml
  tags:
    - part1
    - part1_setup

- name: Verify MongoDB availability
  ansible.builtin.import_tasks: health.yml
  tags:
    - part1
    - part1_health

- name: Verify MongoDB automatic start after boot
  ansible.builtin.import_tasks: autostart_check.yml
  tags:
    - part1
    - part1_autostart_check
